export const SITE = {
  name: "Rudrans Systematic Investment",
  short: "RSI",
  tagline: "Think Beyond Limits",
  owner: "Dharmitsinh Solanki",
  phone: "+91 98257 75948",
  phoneRaw: "+919825775948",
  email: "dharmitsolankifnokite@gmail.com",
  address: {
    line1: "Shop No. G-25, Soham Arcade",
    line2: "Green City Road, Pal",
    city: "Surat - 395009, Gujarat, India",
  },
  whatsapp: "https://wa.me/919825775948",
};

export const NAV = [
  { to: "/", label: "Home" },
  { to: "/who-we-are", label: "Who We Are" },
  { to: "/services", label: "Services" },
  { to: "/products", label: "Products" },
  { to: "/resources", label: "Resources" },
  { to: "/contact", label: "Contact" },
] as const;

export const SERVICES = [
  {
    slug: "financial-planning",
    title: "Financial Planning",
    tagline: "Your complete money roadmap — from where you are to where you want to be.",
    desc: "A comprehensive roadmap aligned with your personal goals, cash-flow, and life stage.",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1400&q=80",
    overview: "Achieving financial freedom is not about luck — it's about a plan. At RSI, we start with a deep understanding of your income, expenses, responsibilities and aspirations to create a personalised financial plan that evolves with you. From managing day-to-day cash flow to building long-term wealth, we guide you through every financial decision with clarity and confidence.",
    highlights: [
      "Detailed cash-flow analysis and budgeting",
      "Net worth assessment and goal mapping",
      "Emergency fund and liquidity planning",
      "Debt management and restructuring",
      "Life-stage milestone planning (marriage, home, education, retirement)",
      "Annual plan review and strategy refresh",
    ],
    process: [
      { step: "Discovery", desc: "We understand your current financial position — income, liabilities, assets and goals." },
      { step: "Analysis", desc: "We map your cash flow, identify gaps and quantify each goal with a time-linked number." },
      { step: "Strategy", desc: "A tailored roadmap is built — investments, insurance, tax and liquidity aligned together." },
      { step: "Execution", desc: "We implement the plan step by step, making each product decision purposeful." },
      { step: "Review", desc: "Quarterly and annual reviews keep your plan updated as life evolves." },
    ],
    suited: "Individuals and families at any income level who want to take control of their financial future with clarity and discipline.",
    faq: [
      { q: "How is financial planning different from investing?", a: "Investing is just one part of financial planning. Planning covers budgeting, insurance, taxes, goals and estate — investing is the engine within that bigger framework." },
      { q: "How often should I review my financial plan?", a: "At least annually, and whenever a major life event occurs — a job change, marriage, child, inheritance or significant expense." },
    ],
  },
  {
    slug: "sip-advisory",
    title: "SIP Advisory",
    tagline: "Turn disciplined monthly savings into life-changing wealth.",
    desc: "Structured investment plans engineered for disciplined, long-horizon wealth creation.",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1400&q=80",
    overview: "A Systematic Investment Plan is the most powerful wealth-creation tool available to Indian investors today. It combines the discipline of regular saving with the mathematics of compounding and the strategy of rupee-cost averaging. Our SIP advisory goes beyond simply setting up a mandate — we choose the right funds, the right amount, and the right time horizon for your specific goals.",
    highlights: [
      "Goal-linked SIP amount calculation",
      "Fund selection across equity, hybrid and debt categories",
      "Step-up SIP planning as income grows",
      "Rupee-cost averaging to manage market volatility",
      "SIP portfolio review and rebalancing",
      "Online and offline mandate setup support",
    ],
    process: [
      { step: "Goal Setting", desc: "We identify what you're saving for — education, home, retirement — and attach a number and timeline to each goal." },
      { step: "Amount Calculation", desc: "We calculate the exact SIP amount needed today to reach your goal, adjusting for inflation." },
      { step: "Fund Selection", desc: "We pick the right fund categories and specific schemes based on your risk tolerance and horizon." },
      { step: "Mandate Setup", desc: "We handle all paperwork and KYC — a smooth, hassle-free onboarding experience." },
      { step: "Ongoing Review", desc: "Annual review of performance, step-up suggestions and fund upgrades when needed." },
    ],
    suited: "Salaried professionals, business owners and homemakers looking to invest regularly and build wealth without timing the market.",
    faq: [
      { q: "What is the minimum SIP amount?", a: "You can start with as little as ₹500 per month. The key is consistency, not the amount." },
      { q: "Can I pause or stop my SIP anytime?", a: "Yes. Most fund houses allow you to pause for up to 3 months or stop entirely with zero penalties." },
    ],
  },
  {
    slug: "mutual-fund-distribution",
    title: "Mutual Fund Distribution",
    tagline: "Professionally managed, diversified portfolios built for your risk appetite.",
    desc: "Curated solutions across equity, debt and hybrid asset classes for any risk appetite.",
    image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=1400&q=80",
    overview: "With thousands of mutual fund schemes available in India, choosing the right ones is overwhelming. As AMFI-registered Mutual Fund Distributors, we simplify this complexity by curating a shortlist of high-quality funds matched to your risk profile, time horizon and financial goals. Our role is not just to sell funds — it is to help you own the right ones.",
    highlights: [
      "ARN-certified, SEBI-regulated distribution",
      "Across all major AMCs — HDFC, SBI, ICICI, Mirae, Axis and more",
      "Equity, debt, hybrid, liquid and sectoral fund options",
      "Regular performance benchmarking",
      "Lumpsum and SIP investment modes",
      "Zero advisory fee — commissions paid by AMC",
    ],
    process: [
      { step: "Risk Profiling", desc: "We assess your risk tolerance through a structured questionnaire." },
      { step: "Asset Allocation", desc: "We decide the right equity-debt split based on your goals and horizon." },
      { step: "Fund Shortlisting", desc: "3–5 high-conviction fund recommendations based on track record and philosophy." },
      { step: "Investment", desc: "Lumpsum or SIP — we handle the entire transaction and documentation." },
      { step: "Review", desc: "Periodic performance review against benchmark and peer comparison." },
    ],
    suited: "Anyone seeking to grow wealth systematically — from conservative savers to aggressive equity investors.",
    faq: [
      { q: "Are mutual funds regulated?", a: "Yes. All mutual funds in India are regulated by SEBI and governed by a Board of Trustees. Your money is held in a Trust separate from the AMC." },
      { q: "How much do you charge for mutual fund distribution?", a: "Nothing directly. We earn distributor commissions from the AMC, built into the regular plan NAV. Your capital earns returns net of all costs." },
    ],
  },
  {
    slug: "tax-saving-solutions",
    title: "Tax Saving Solutions",
    tagline: "Invest smarter. Pay less tax. Grow more wealth.",
    desc: "ELSS and tax-efficient instruments that grow capital while reducing your liability.",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1400&q=80",
    overview: "Paying tax is a duty; paying more than necessary is a mistake. Under Section 80C and other provisions, the Indian tax code allows deductions of up to ₹1.5 lakh per year on qualifying investments. We help you use every legitimate rupee of this allowance — and direct it into instruments that also create long-term wealth, not just reduce tax for a year.",
    highlights: [
      "ELSS (Equity Linked Savings Scheme) — shortest 80C lock-in at 3 years",
      "PPF (Public Provident Fund) — risk-free long-term savings",
      "NPS — additional ₹50,000 deduction under 80CCD(1B)",
      "Tax-efficient SWP and Dividend Reinvestment strategies",
      "Capital gains harvesting advice",
      "Tax-loss harvesting at year-end",
    ],
    process: [
      { step: "Tax Assessment", desc: "We review your total income, existing deductions and remaining 80C headroom." },
      { step: "Instrument Selection", desc: "We recommend the right mix of ELSS, PPF or NPS based on your liquidity needs and risk appetite." },
      { step: "Investment", desc: "We process your investments before the financial year deadline." },
      { step: "Documentation", desc: "We provide you with all certificates and statements required for ITR filing." },
      { step: "Next Year Planning", desc: "We start early — systematic tax planning across 12 months rather than a March rush." },
    ],
    suited: "Salaried employees and business owners with taxable income above the basic exemption limit who want to reduce tax and build wealth simultaneously.",
    faq: [
      { q: "What is ELSS and why is it better than other 80C options?", a: "ELSS is an equity mutual fund with a 3-year lock-in (shortest among all 80C instruments), offering market-linked returns that have historically outpaced PPF and FD rates." },
      { q: "Can I invest in ELSS via SIP?", a: "Yes — SIP into ELSS is the most efficient approach, as each instalment has its own 3-year lock-in, giving you staggered liquidity." },
    ],
  },
  {
    slug: "insurance-planning",
    title: "Insurance Planning",
    tagline: "Because financial security is incomplete without protection.",
    desc: "Term, health and family-protection strategies sized to your real-world responsibilities.",
    image: "https://images.unsplash.com/photo-1556742044-3c52d6e88c62?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1556742044-3c52d6e88c62?w=1400&q=80",
    overview: "Building wealth without protection is like building a house without a foundation. A single medical emergency or untimely death can undo decades of savings in an instant. RSI takes a needs-based approach to insurance — we calculate exactly how much cover you need based on your income, liabilities and dependents, not on what pays the highest commission.",
    highlights: [
      "Pure term insurance — high cover at minimal premium",
      "Family floater and individual health insurance plans",
      "Critical illness and accidental disability riders",
      "Income replacement analysis",
      "Child protection and education cover",
      "Annual insurance review as life changes",
    ],
    process: [
      { step: "Needs Analysis", desc: "We calculate your Human Life Value and outstanding liabilities to determine the right cover." },
      { step: "Product Comparison", desc: "We compare products across multiple insurers — claims ratio, network, premium and features." },
      { step: "Recommendation", desc: "A clear recommendation with reasoning — no pressure, no incentive-driven selling." },
      { step: "Policy Issuance", desc: "We handle the complete proposal, medical coordination and policy delivery." },
      { step: "Claims Support", desc: "If the worst happens, we guide your family through the claims process step by step." },
    ],
    suited: "Primary earners, married individuals, parents and anyone with financial dependents who want complete protection for their family.",
    faq: [
      { q: "How much life insurance do I need?", a: "A common benchmark is 10–15x your annual income. But the right number depends on your outstanding loans, number of dependents and long-term goals — we calculate this precisely for you." },
      { q: "Should I buy term or endowment insurance?", a: "Term insurance gives pure protection at the lowest cost. Endowment plans mix insurance with savings — usually at poor returns for both. We always recommend keeping them separate." },
    ],
  },
  {
    slug: "retirement-planning",
    title: "Retirement Planning",
    tagline: "Work because you want to — not because you have to.",
    desc: "Decade-by-decade frameworks that translate today's savings into tomorrow's freedom.",
    image: "https://images.unsplash.com/photo-1580918256819-53b4d09c74d8?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580918256819-53b4d09c74d8?w=1400&q=80",
    overview: "Retirement is not an age — it's a number. The number represents the corpus you need to live comfortably for the rest of your life without depending on anyone. We help you find your number, build toward it systematically, and manage it wisely once you get there. Whether retirement is 30 years or 5 years away, we have a framework for you.",
    highlights: [
      "Retirement corpus calculation with inflation adjustment",
      "NPS and Pension fund investments",
      "Balanced advantage and dynamic asset allocation funds",
      "SWP (Systematic Withdrawal Plan) setup for post-retirement income",
      "Senior citizen income optimisation",
      "Estate and succession planning basics",
    ],
    process: [
      { step: "Retirement Goal", desc: "We estimate your post-retirement monthly expense and adjust for 25–30 years of inflation." },
      { step: "Corpus Calculation", desc: "We calculate the exact corpus needed at your target retirement age." },
      { step: "Investment Pathway", desc: "We build an equity-heavy growth phase and a debt-transition phase as retirement nears." },
      { step: "NPS Integration", desc: "We help you maximise NPS benefits for tax savings and guaranteed pension." },
      { step: "Withdrawal Strategy", desc: "On retirement, we structure SWPs and income plans that last a lifetime." },
    ],
    suited: "Working professionals of any age — the earlier you start, the less you need to invest each month to reach your retirement goal.",
    faq: [
      { q: "How early should I start planning for retirement?", a: "The day you earn your first salary. Starting at 25 vs 35 can mean investing 4x less per month to reach the same corpus." },
      { q: "What is NPS and should I invest in it?", a: "The National Pension System is a government-backed retirement scheme offering equity exposure, low cost and an extra ₹50,000 tax deduction. It's a strong complement to mutual fund retirement planning." },
    ],
  },
  {
    slug: "child-education-planning",
    title: "Child Education Planning",
    tagline: "Your child's dream should never wait for your wallet.",
    desc: "Goal-anchored portfolios that mature in step with your child's milestones.",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1400&q=80",
    overview: "Education costs in India are rising at 10–12% per year — far faster than general inflation. A course that costs ₹15 lakh today will cost ₹40+ lakh in 10 years. We help parents build dedicated education funds that grow in lockstep with these rising costs, ensuring your child's best future is never a financial compromise.",
    highlights: [
      "Education cost estimation with realistic inflation",
      "Dedicated goal-linked SIP portfolios",
      "Age-based asset allocation glide path",
      "Child insurance and waiver-of-premium benefit planning",
      "Multiple goal tracking (school, college, abroad)",
      "Fund maturity aligned with education milestone",
    ],
    process: [
      { step: "Goal Definition", desc: "We identify your child's education goals — UG, PG, abroad, technical — with timelines." },
      { step: "Cost Projection", desc: "We estimate future education costs with realistic inflation assumptions." },
      { step: "SIP Calculation", desc: "We calculate the monthly SIP needed today to meet that cost when the time comes." },
      { step: "Portfolio Build", desc: "A dedicated education portfolio is created, separate from your other investments." },
      { step: "Annual Review", desc: "We track progress against the goal and adjust contributions if needed." },
    ],
    suited: "Parents of children from newborn to 15 years who want to systematically fund education without compromising their own retirement or lifestyle.",
    faq: [
      { q: "Should I use child insurance plans for education?", a: "Traditional child insurance plans often give poor returns. A pure term plan for parents + equity mutual fund SIP is significantly more efficient for education funding." },
      { q: "What if my child gets a scholarship or chooses a different path?", a: "The corpus is yours — you can redirect it to another goal such as a wedding fund, a business seed or retirement." },
    ],
  },
  {
    slug: "portfolio-review",
    title: "Portfolio Review",
    tagline: "A portfolio that isn't reviewed is a portfolio that drifts.",
    desc: "Periodic re-balancing, performance audit and strategy refinement against your benchmarks.",
    image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=1400&q=80",
    overview: "Markets change. Life changes. Your portfolio should change too. RSI conducts periodic portfolio reviews that go beyond just checking returns — we audit fund quality, review asset allocation drift, check if your portfolio still matches your goals, and make precise adjustments. A well-reviewed portfolio is the difference between hitting your targets and falling short.",
    highlights: [
      "Performance audit against benchmark and category average",
      "Asset allocation drift correction and rebalancing",
      "Fund quality review and replacement if needed",
      "Tax-efficiency assessment and harvesting",
      "Goal progress tracking",
      "Risk exposure re-evaluation after life events",
    ],
    process: [
      { step: "Portfolio Audit", desc: "We collect all your existing investments — funds, FDs, stocks, insurance — for a complete picture." },
      { step: "Performance Analysis", desc: "We compare each fund's performance against its benchmark and category peers." },
      { step: "Allocation Review", desc: "We check if your equity-debt split still matches your current risk tolerance and time horizon." },
      { step: "Recommendations", desc: "We prepare a clear action plan — which funds to continue, pause, switch or redeem." },
      { step: "Implementation", desc: "We execute the agreed changes and update your financial plan accordingly." },
    ],
    suited: "Investors with existing portfolios that haven't been reviewed in 12+ months, or those who have accumulated investments across multiple advisors with no clear strategy.",
    faq: [
      { q: "How often should my portfolio be reviewed?", a: "Minimum annually, ideally twice a year. Additionally, after any major life event — job change, marriage, childbirth, inheritance or significant income change." },
      { q: "What if I have investments from multiple advisors?", a: "We consolidate and review everything together, giving you a complete picture before making any recommendations." },
    ],
  },
];

export const PRODUCTS = [
  {
    slug: "mutual-funds",
    title: "Mutual Funds",
    overview: "A mutual fund pools money from thousands of investors to purchase a diversified portfolio of stocks, bonds or other securities — managed by professional fund managers. It's the most accessible, liquid and regulated wealth-creation tool available to Indian investors today.",
    image: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=1400&q=80",
    tagline: "Diversified, professionally managed wealth creation for every investor.",
    whyChoose: "Mutual funds give you access to a diversified portfolio with as little as ₹500. Your money is managed by professional fund managers with dedicated research teams — expertise you'd otherwise only get with crores of investable assets.",
    benefits: ["Daily liquidity — redeem anytime", "Professional fund management", "Wide diversification across 30–100 securities", "Transparent NAV updated daily", "SEBI-regulated with trustee oversight"],
    types: [
      { name: "Equity Funds", desc: "Invest predominantly in stocks. High risk, high potential return. Ideal for 5+ year horizon." },
      { name: "Debt Funds", desc: "Invest in bonds and fixed-income instruments. Lower risk, stable returns. Good for 1–3 years." },
      { name: "Hybrid Funds", desc: "Mix of equity and debt. Balanced risk-return. Good for moderate investors." },
      { name: "Liquid Funds", desc: "Invest in overnight or very short-term debt. Ideal for emergency funds and short-term parking." },
    ],
    suited: "First-time investors, salaried professionals, business owners and HNIs looking for a regulated, transparent and liquid vehicle for long-term wealth creation.",
    minInvestment: "₹500 (SIP) / ₹1,000 (Lumpsum)",
    riskLevel: "Low to High (varies by fund type)",
    horizon: "1 year to 20+ years",
  },
  {
    slug: "sip",
    title: "Systematic Investment Plan (SIP)",
    overview: "A SIP lets you invest a fixed amount into a mutual fund every month automatically — like an EMI, but for wealth creation. It harnesses the power of compounding, eliminates the need to time the market and instils financial discipline effortlessly.",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1400&q=80",
    tagline: "Small, consistent investments. Extraordinary long-term results.",
    whyChoose: "A ₹10,000 monthly SIP for 20 years at 12% returns grows to over ₹99 lakh — on a total investment of just ₹24 lakh. The difference of ₹75 lakh is pure compounding. SIPs also average out market highs and lows through rupee-cost averaging, reducing the impact of volatility.",
    benefits: ["Starts at just ₹500/month", "Automated monthly debit — no effort needed", "Rupee-cost averaging reduces market timing risk", "Step-up facility as your income grows", "Pause or stop anytime without penalty"],
    types: [
      { name: "Regular SIP", desc: "Fixed monthly amount invested consistently." },
      { name: "Step-Up SIP", desc: "Amount increases annually (e.g. by 10%) in line with your income growth." },
      { name: "Trigger SIP", desc: "Invests additional amounts on market corrections — for tactical investors." },
      { name: "Perpetual SIP", desc: "No end date — runs until you stop it. Best for long-term wealth creation." },
    ],
    suited: "Salaried professionals, homemakers managing household savings and young earners who want to build wealth systematically without monitoring markets daily.",
    minInvestment: "₹500/month",
    riskLevel: "Depends on underlying fund",
    horizon: "3 years minimum, ideally 10–20 years",
  },
  {
    slug: "elss",
    title: "ELSS — Tax Saving Mutual Funds",
    overview: "Equity Linked Savings Schemes (ELSS) are equity mutual funds with a mandatory 3-year lock-in that qualify for tax deduction up to ₹1.5 lakh under Section 80C. They offer the shortest lock-in among all 80C instruments while providing equity-level returns.",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1400&q=80",
    tagline: "Save tax today. Build wealth for tomorrow.",
    whyChoose: "Most 80C instruments lock your money for 5–15 years at fixed returns. ELSS locks in for just 3 years while giving you equity market exposure — historically 12–15% CAGR. It's the most efficient way to save tax and grow wealth simultaneously.",
    benefits: ["Tax deduction up to ₹1.5 lakh under Section 80C", "Shortest 80C lock-in — only 3 years", "Equity market-linked returns (historically 12–15% CAGR)", "Available via SIP — staggered liquidity", "Long-term capital gains taxed at only 10% (above ₹1 lakh)"],
    types: [
      { name: "Lumpsum ELSS", desc: "Invest the full ₹1.5 lakh before March 31 for the current year's 80C deduction." },
      { name: "SIP ELSS", desc: "Monthly SIP — each instalment has its own 3-year lock-in, giving staggered liquidity." },
    ],
    suited: "Salaried employees and business owners with taxable income above ₹5 lakh who want to maximise 80C deductions while building long-term equity wealth.",
    minInvestment: "₹500/month (SIP) or ₹1,000 (Lumpsum)",
    riskLevel: "Moderately High (equity market exposure)",
    horizon: "3 years minimum, ideally 5–10 years",
  },
  {
    slug: "health-insurance",
    title: "Health Insurance",
    overview: "Health insurance covers hospitalisation, surgical procedures, critical illnesses and day-care treatments — protecting your savings from the financial shock of a medical emergency. With healthcare inflation running at 15% annually, adequate health cover is non-negotiable.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=1400&q=80",
    tagline: "Protect your health. Protect your savings.",
    whyChoose: "Medical costs can wipe out years of savings in a single hospitalisation. A comprehensive health insurance plan ensures that a health crisis never becomes a financial crisis — and your investment portfolio stays untouched.",
    benefits: ["Cashless treatment at 10,000+ network hospitals", "Pre and post-hospitalisation expenses covered", "No-claim bonus — sum insured increases each year", "Tax benefit under Section 80D", "Lifetime renewability guarantee"],
    types: [
      { name: "Individual Plan", desc: "Separate sum insured for each family member. Best when health risks are unequal." },
      { name: "Family Floater", desc: "One sum insured shared by the whole family. Cost-efficient for young families." },
      { name: "Critical Illness Plan", desc: "Lump-sum payout on diagnosis of 30+ critical illnesses. Income replacement benefit." },
      { name: "Super Top-Up", desc: "Enhances your existing cover at low cost. Ideal if employer cover is insufficient." },
    ],
    suited: "Everyone with dependents, self-employed individuals without employer cover, senior citizens and anyone with a family history of serious illness.",
    minInvestment: "₹5,000–₹20,000/year (approx., varies by age and cover)",
    riskLevel: "Not applicable (protection product)",
    horizon: "Annual renewable (lifetime)",
  },
  {
    slug: "life-insurance",
    title: "Life Insurance",
    overview: "Life insurance ensures that if you're no longer there, your family's financial future remains secure — debts get paid, children's education continues and your spouse maintains their standard of living. We recommend pure term insurance — the most affordable way to secure a large cover.",
    image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=1400&q=80",
    tagline: "Your presence protects them. Term insurance ensures your absence doesn't break them.",
    whyChoose: "A ₹1 crore term plan for a 30-year-old costs as little as ₹800/month. No other financial instrument provides this level of income-replacement protection at this cost. It's the most important purchase a breadwinner can make.",
    benefits: ["High sum assured at low premium", "Income replacement for dependents", "Outstanding loan payoff protection", "Add riders — critical illness, accident, waiver of premium", "Tax benefit on premium under Section 80C"],
    types: [
      { name: "Pure Term Plan", desc: "Death benefit only. Highest cover at the lowest cost. Our default recommendation." },
      { name: "Term with Return of Premium", desc: "Premiums returned if you survive the term. Higher cost — suitable for specific cases." },
      { name: "Group Term Insurance", desc: "Employer-provided cover — usually insufficient. Always supplement with a personal term plan." },
      { name: "ULIP", desc: "Market-linked insurance. Generally not recommended — separating insurance and investment is more efficient." },
    ],
    suited: "All primary earners, married individuals with a spouse or children, and anyone with outstanding home loans or financial liabilities.",
    minInvestment: "₹500–₹2,000/month (pure term, ₹1 Cr cover, age 30)",
    riskLevel: "Not applicable (protection product)",
    horizon: "20–40 years (match with youngest dependent's self-sufficiency)",
  },
  {
    slug: "retirement-solutions",
    title: "Retirement Solutions",
    overview: "Retirement planning is about building a corpus large enough to replace your active income indefinitely. We combine the National Pension System, balanced advantage funds, dividend-paying funds and SWPs to build a retirement income machine that lasts 25–30 years post-retirement.",
    image: "https://images.unsplash.com/photo-1580918256819-53b4d09c74d8?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580918256819-53b4d09c74d8?w=1400&q=80",
    tagline: "Build the corpus today. Retire on your own terms tomorrow.",
    whyChoose: "Most Indians underestimate how much they need for retirement. With life expectancy rising to 80+, you may need 25–30 years of post-retirement income. We help you build that corpus systematically — with inflation protection built in.",
    benefits: ["Inflation-adjusted corpus calculation", "NPS for tax savings and guaranteed pension", "Equity exposure in growth phase for inflation-beating returns", "SWP setup for regular monthly income post-retirement", "Capital preservation in final years before retirement"],
    types: [
      { name: "NPS (National Pension System)", desc: "Government-backed retirement scheme. Low cost, equity exposure, ₹50,000 extra tax deduction." },
      { name: "Balanced Advantage Funds", desc: "Dynamic equity-debt allocation — reduces volatility as retirement nears." },
      { name: "SWP (Systematic Withdrawal Plan)", desc: "Regular monthly income from corpus without depleting principal fast." },
      { name: "Senior Citizen Savings Scheme", desc: "Government-backed, 8%+ return, quarterly payout. Good for post-retirement liquidity." },
    ],
    suited: "Working professionals 25–55 years old who want to retire comfortably without financial dependence on children or social security.",
    minInvestment: "₹5,000/month (NPS min ₹1,000/year)",
    riskLevel: "Low to Moderate (reduces as retirement nears)",
    horizon: "10–35 years depending on retirement age",
  },
  {
    slug: "child-future-planning",
    title: "Child Future Planning",
    overview: "Child future plans are goal-linked equity portfolios designed to mature exactly when your child needs the money — for school fees, college admission, study abroad or a wedding. We align asset allocation, fund selection and SIP amount with your child's age and the specific milestone.",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1400&q=80",
    tagline: "Their future. Fully funded. On time.",
    whyChoose: "Education costs in India are rising at 10–12% annually. A college education costing ₹15 lakh today will cost ₹40 lakh in 10 years. Planning early with equity exposure is the only way to outpace this inflation and ensure your child's dreams are never constrained by finances.",
    benefits: ["Dedicated goal-linked portfolio per child", "Age-based glide path — equity heavy early, debt-heavy near goal", "Automatic step-up as your income grows", "Separate from your retirement savings", "Progress tracking with alerts if you fall behind"],
    types: [
      { name: "Education Fund SIP", desc: "Monthly equity SIP building toward college or higher education corpus." },
      { name: "Child Insurance Plan", desc: "Waiver of premium if parent passes away — SIP continues automatically." },
      { name: "Sukanya Samriddhi Yojana", desc: "Government scheme for girl child — 8%+ tax-free returns." },
      { name: "Multi-goal Child Plan", desc: "Multiple SIPs — one for school, one for college, one for wedding — tracked separately." },
    ],
    suited: "Parents of children aged 0–15 who want to systematically fund education and other milestones without last-minute financial stress.",
    minInvestment: "₹1,000/month",
    riskLevel: "Moderate to High (reduces as milestone nears)",
    horizon: "5–20 years",
  },
];

export const ARTICLES = [
  { title: "The Quiet Power of Compounding", read: "5 min read", excerpt: "Why patience, not prediction, builds the most reliable wealth." },
  { title: "Benefits of Investing Through SIPs", read: "4 min read", excerpt: "How automated discipline outperforms timing the market." },
  { title: "Mutual Funds, Simplified", read: "6 min read", excerpt: "A clear introduction to asset classes, AMCs and what to look for." },
  { title: "Insurance Planning Essentials", read: "5 min read", excerpt: "The right amount of cover at the right life stage." },
  { title: "Smart Financial Habits", read: "3 min read", excerpt: "Five practices that quietly transform your finances over a decade." },
  { title: "Decoding ELSS for Tax Season", read: "4 min read", excerpt: "Why ELSS is the most efficient 80C tool for long-term investors." },
];

export const FAQS = [
  { q: "What is a SIP and how does it work?", a: "A Systematic Investment Plan lets you invest a fixed amount monthly into a mutual fund. It averages out market volatility and turns small contributions into significant corpus through compounding." },
  { q: "How much should I start investing with?", a: "You can begin with as little as ₹500 per month. What matters more than the amount is the consistency and the alignment with your long-term goals." },
  { q: "Are mutual funds safe?", a: "Mutual funds are regulated by SEBI and managed by professional fund houses. While market-linked, diversified long-horizon investing has historically created reliable wealth." },
  { q: "How does RSI earn?", a: "We earn standard distributor commissions paid by Asset Management Companies. You pay no additional fee for our advisory and ongoing support." },
  { q: "Can I withdraw my investment anytime?", a: "Open-ended mutual funds offer daily liquidity. ELSS has a 3-year lock-in. We help you structure investments so liquidity matches your goals." },
];

export const TESTIMONIALS = [
  { name: "Rakesh M.", role: "Business Owner, Surat", quote: "Dharmit helped me move from scattered investments to a clear, goal-linked plan. Five years in, my portfolio finally feels intentional." },
  { name: "Priya & Karan S.", role: "Young Family, Pal", quote: "We started SIPs with RSI for our daughter's education. The reviews and honesty make all the difference." },
  { name: "Ankit V.", role: "IT Professional", quote: "What I value most is the transparency. No pressure, no jargon — just clear advice that respects my long-term horizon." },
  { name: "Meera D.", role: "Doctor", quote: "Insurance, tax planning, retirement — handled in one place with a calm, structured approach. Highly recommend." },
];

export const JOURNEY = [
  { step: "Dream", desc: "Define the life milestones you want your wealth to fund." },
  { step: "Plan", desc: "Map cash-flow, risk profile and time horizon into a strategy." },
  { step: "Invest", desc: "Deploy capital systematically across diversified instruments." },
  { step: "Grow", desc: "Let compounding work while we review and rebalance." },
  { step: "Achieve", desc: "Reach your goals with confidence and a clear exit plan." },
];

export const VALUES = ["Trust", "Integrity", "Commitment", "Transparency", "Growth"];

export const TEAM = [
  {
    name: "Dharmitsinh Solanki",
    role: "Founder & Principal Advisor",
    image: "/dharmit.jpg",
    bio: "Dharmitsinh Solanki founded Rudrans Systematic Investment with a single conviction — that every Indian family deserves honest, personalised financial guidance. With over 8 years of experience as an AMFI-registered Mutual Fund Distributor and certified financial advisor, he has helped 240+ investor families in Surat and Gujarat build systematic wealth through disciplined SIP planning, mutual fund investments and comprehensive protection strategies. His approach is built on transparency, zero commission-driven selling and long-term client relationships. He holds an ARN certification and is a member of the Financial Planning Association of India.",
    credentials: ["ARN Certified MFD", "AMFI Registered", "8+ Years Experience", "240+ Client Families"],
  },
  {
    name: "Suresh Sharma",
    role: "Senior Insurance & Protection Advisor",
    image: null,
    bio: "Suresh Sharma brings deep expertise in risk management, life insurance and health protection planning to the RSI team. With over a decade in the insurance advisory space, he specialises in needs-based insurance planning — ensuring each client has exactly the right coverage without overpaying. His philosophy is simple: insurance should protect everything you've worked hard to build. He advises clients on term insurance, health covers, critical illness plans and group protection solutions across leading insurance companies.",
    credentials: ["Certified Insurance Advisor", "IRDAI Licenced", "10+ Years Experience", "Health & Life Specialist"],
  },
];
